version: '3'
services:
  db:
    image: postgres
    volumes:
      - ../../tmp/db:/var/lib/postgresql/data
  web:
    build: ../../
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../../:/myapp
    environment:
      REDIS_URL: redis://redis:6379/12
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  sidekiq:
    build: ../../
    command: bundle exec sidekiq
    volumes:
      - ../../:/myapp
    environment:
      REDIS_URL: redis://redis:6379/12
    depends_on:
      - redis
